# Generated by Django 3.1 on 2020-08-24 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='Course Name')),
                ('exam_weight', models.IntegerField(default=0, verbose_name='Exam Weight')),
                ('homework_weight', models.IntegerField(default=0, verbose_name='Homework Weight')),
                ('quiz_weight', models.IntegerField(default=0, verbose_name='Quiz Weight')),
                ('essay_weight', models.IntegerField(default=0, verbose_name='Essay Weight')),
                ('final_weight', models.IntegerField(default=0, verbose_name='Final Weight')),
                ('midterm_weight', models.IntegerField(default=0, verbose_name='Midterm Weight')),
                ('lab_weight', models.IntegerField(default=0, verbose_name='Lab Weight')),
                ('extra_credit_weight', models.IntegerField(default=0, verbose_name='Extra-Credit Weight')),
                ('grade', models.IntegerField(default=100, verbose_name='Grade')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=135, verbose_name='Title')),
                ('details', models.TextField(blank=True, max_length=350, null=True, verbose_name='Details')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('location', models.CharField(blank=True, max_length=450, null=True, verbose_name='Location')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=150, verbose_name='Assignment Title')),
                ('assignment_detail', models.TextField(blank=True, max_length=350, null=True, verbose_name='Assignment Detail')),
                ('assignment_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Assignment Due Date')),
                ('assignment_role', models.CharField(choices=[('Exam', 'Exam'), ('Homework', 'Homework'), ('Quiz', 'Quiz'), ('Essay', 'Essay'), ('Final', 'Final'), ('Midterm', 'Midterm'), ('Lab', 'Lab'), ('Extra Credit', 'Extra Credit')], max_length=30, verbose_name='Assignment Role')),
                ('assignment_duration', models.DurationField(verbose_name='Assignment Duration')),
                ('repeat', models.CharField(choices=[('NEVER', 'Never'), ('DAILY', 'Every Day'), ('WEEKDAY', 'Every Weekday'), ('WEEKLY', 'Every Week'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Every Month'), ('YEARLY', 'Every Year')], default='NEVER', max_length=15, verbose_name='Repeat')),
                ('end_repeat', models.DateField(blank=True, null=True, verbose_name='Repeat Cycle')),
                ('grade', models.IntegerField(default=100, verbose_name='Grade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.course')),
            ],
        ),
    ]
